use crate::data::AdifData;
use crate::enumerations::EnumerationType::{
    AntPath, ArrlSection, Band, ContestId, Continent, DxccEntityCode, Mode, MorseKeyType,
    PropagationMode, QslRcvd, QslSent, QslVia, QsoComplete, QsoUploadStatus, Region, SubMode,
};
use crate::error::AdifError;
use crate::field::FieldName;
use crate::fields::data::DataType;
use radif_macros::{AdifData, AutoDisplay};
use std::string::String;

#[derive(Debug, Clone, PartialEq, Eq, AutoDisplay, AdifData)]
#[allow(non_camel_case_types)]
pub enum QSOFieldName {
    ADDRESS,
    ADDRESS_INTL,
    AGE,
    ALTITUDE,
    ANT_AZ,
    ANT_EL,
    ANT_PATH,
    ARRL_SECT,
    AWARD_GRANTED,
    AWARD_SUBMITTED,
    A_INDEX,
    BAND,
    BAND_RX,
    CALL,
    CHECK,
    CLASS,
    CLUBLOG_QSO_UPLOAD_DATE,
    CLUBLOG_QSO_UPLOAD_STATUS,
    CNTY,
    CNTY_ALT,
    COMMENT,
    COMMENT_INTL,
    CONT,
    CONTACTED_OP,
    CONTEST_ID,
    COUNTRY,
    COUNTRY_INTL,
    CQZ,
    CREDIT_SUBMITTED,
    CREDIT_GRANTED,
    DARC_DOK,
    DCL_QSLRDATE,
    DCL_QSLSDATE,
    DCL_QSL_RCVD,
    DCL_QSL_SENT,
    DISTANCE,
    DXCC,
    EMAIL,
    EQ_CALL,
    EQSL_QSLRDATE,
    EQSL_QSLSDATE,
    EQSL_QSL_RCVD,
    EQSL_QSL_SENT,
    FISTS,
    FISTS_CC,
    FORCE_INIT,
    FREQ,
    FREQ_RX,
    GRIDSQUARE,
    GRIDSQUARE_EXT,
    GUEST_OP,
    HAMLOGEU_QSO_UPLOAD_DATE,
    HAMLOGEU_QSO_UPLOAD_STATUS,
    HAMQTH_QSO_UPLOAD_DATE,
    HAMQTH_QSO_UPLOAD_STATUS,
    HRDLOG_QSO_UPLOAD_DATE,
    HRDLOG_QSO_UPLOAD_STATUS,
    IOTA,
    IOTA_ISLAND_ID,
    ITUZ,
    K_INDEX,
    LAT,
    LON,
    LOTW_QSLRDATE,
    LOTW_QSLSDATE,
    LOTW_QSL_RCVD,
    LOTW_QSL_SENT,
    MAX_BURSTS,
    MODE,
    MORSE_KEY_INFO,
    MORSE_KEY_TYPE,
    MS_SHOWER,
    MY_ALTITUDE,
    MY_ANTENNA,
    MY_ANTENNA_INTL,
    MY_ARRL_SECT,
    MY_CITY,
    MY_CITY_INTL,
    MY_CNTY,
    MY_CNTY_ALT,
    MY_COUNTRY,
    MY_COUNTRY_INTL,
    MY_CQ_ZONE,
    MY_DARC_DOK,
    MY_DXCC,
    MY_FISTS,
    MY_GRIDSQUARE,
    MY_GRIDSQUARE_EXT,
    MY_IOTA,
    MY_IOTA_ISLAND_ID,
    MY_ITU_ZONE,
    MY_LAT,
    MY_LON,
    MY_MORSE_KEY_INFO,
    MY_MORSE_KEY_TYPE,
    MY_NAME,
    MY_NAME_INTL,
    MY_POSTAL_CODE,
    MY_POSTAL_CODE_INTL,
    MY_POTA_REF,
    MY_RIG,
    MY_RIG_INTL,
    MY_SIG,
    MY_SIG_INTL,
    MY_SIG_INFO,
    MY_SIG_INFO_INTL,
    MY_SOTA_REF,
    MY_STATE,
    MY_STREET,
    MY_STREET_INTL,
    MY_USACA_COUNTIES,
    MY_VUCC_GRIDS,
    MY_WWFF_REF,
    NAME,
    NAME_INTL,
    NOTES,
    NOTES_INTL,
    NR_BURSTS,
    NR_PINGS,
    OPERATOR,
    OWNER_CALLSIGN,
    PFX,
    POTA_REF,
    PRECEDENCE,
    PROP_MODE,
    PUBLIC_KEY,
    QRZCOM_QSO_DOWNLOAD_DATE,
    QRZCOM_QSO_DOWNLOAD_STATUS,
    QRZCOM_QSO_UPLOAD_DATE,
    QRZCOM_QSO_UPLOAD_STATUS,
    QSLMSG,
    QSLMSG_INTL,
    QSLMSG_RCVD,
    QSLRDATE,
    QSLSDATE,
    QSL_RCVD,
    QSL_RCVD_VIA,
    QSL_SENT,
    QSL_SENT_VIA,
    QSL_VIA,
    QSO_COMPLETE,
    QSO_DATE,
    QSO_DATE_OFF,
    QSO_RANDOM,
    QTH,
    QTH_INTL,
    REGION,
    RIG,
    RIG_INTL,
    RST_RCVD,
    RST_SENT,
    RX_PWR,
    SAT_MODE,
    SAT_NAME,
    SFI,
    SIG,
    SIG_INTL,
    SIG_INFO,
    SIG_INFO_INTL,
    SILENT_KEY,
    SKCC,
    SOTA_REF,
    SRX,
    SRX_STRING,
    STATE,
    STATION_CALLSIGN,
    STX,
    STX_STRING,
    SUBMODE,
    SWL,
    TEN_TEN,
    TIME_OFF,
    TIME_ON,
    TX_PWR,
    UKSMG,
    USACA_COUNTIES,
    VE_PROV,
    VUCC_GRIDS,
    WEB,
    WWFF_REF,
}

impl FieldName for QSOFieldName {
    fn get_data_type(&self) -> DataType {
        match self {
            QSOFieldName::ADDRESS => DataType::MultilineString,
            QSOFieldName::ADDRESS_INTL => DataType::IntlMultilineString,
            QSOFieldName::AGE => DataType::Number,
            QSOFieldName::ALTITUDE => DataType::Number,
            QSOFieldName::ANT_AZ => DataType::Number,
            QSOFieldName::ANT_EL => DataType::Number,
            QSOFieldName::ANT_PATH => DataType::Enumeration(AntPath),
            QSOFieldName::ARRL_SECT => DataType::Enumeration(ArrlSection),
            QSOFieldName::AWARD_GRANTED => DataType::SponsoredAwardList,
            QSOFieldName::AWARD_SUBMITTED => DataType::SponsoredAwardList,
            QSOFieldName::A_INDEX => DataType::Number,
            QSOFieldName::BAND => DataType::Enumeration(Band),
            QSOFieldName::BAND_RX => DataType::Enumeration(Band),
            QSOFieldName::CALL => DataType::String,
            QSOFieldName::CHECK => DataType::String,
            QSOFieldName::CLASS => DataType::String,
            QSOFieldName::CLUBLOG_QSO_UPLOAD_DATE => DataType::Date,
            QSOFieldName::CLUBLOG_QSO_UPLOAD_STATUS => DataType::Enumeration(QsoUploadStatus),
            QSOFieldName::CNTY => DataType::SecondarySubdivisionList,
            QSOFieldName::CNTY_ALT => DataType::SecondaryAdministrativeSubdivisionListAlt,
            QSOFieldName::COMMENT => DataType::String,
            QSOFieldName::COMMENT_INTL => DataType::IntlString,
            QSOFieldName::CONT => DataType::Enumeration(Continent),
            QSOFieldName::CONTACTED_OP => DataType::String,
            QSOFieldName::CONTEST_ID => DataType::Enumeration(ContestId),
            QSOFieldName::COUNTRY => DataType::String,
            QSOFieldName::COUNTRY_INTL => DataType::IntlString,
            QSOFieldName::CQZ => DataType::PositiveInteger,
            QSOFieldName::CREDIT_SUBMITTED => DataType::CreditList,
            QSOFieldName::CREDIT_GRANTED => DataType::CreditList,
            QSOFieldName::DARC_DOK => DataType::String,
            QSOFieldName::DCL_QSLRDATE => DataType::Date,
            QSOFieldName::DCL_QSLSDATE => DataType::Date,
            QSOFieldName::DCL_QSL_RCVD => DataType::Enumeration(QslRcvd),
            QSOFieldName::DCL_QSL_SENT => DataType::Enumeration(QslSent),
            QSOFieldName::DISTANCE => DataType::Number,
            QSOFieldName::DXCC => DataType::Enumeration(DxccEntityCode),
            QSOFieldName::EMAIL => DataType::String,
            QSOFieldName::EQ_CALL => DataType::String,
            QSOFieldName::EQSL_QSLRDATE => DataType::Date,
            QSOFieldName::EQSL_QSLSDATE => DataType::Date,
            QSOFieldName::EQSL_QSL_RCVD => DataType::Enumeration(QslRcvd),
            QSOFieldName::EQSL_QSL_SENT => DataType::Enumeration(QslSent),
            QSOFieldName::FISTS => DataType::PositiveInteger,
            QSOFieldName::FISTS_CC => DataType::PositiveInteger,
            QSOFieldName::FORCE_INIT => DataType::Boolean,
            QSOFieldName::FREQ => DataType::Number,
            QSOFieldName::FREQ_RX => DataType::Number,
            QSOFieldName::GRIDSQUARE => DataType::GridSquare,
            QSOFieldName::GRIDSQUARE_EXT => DataType::GridSquareExt,
            QSOFieldName::GUEST_OP => DataType::String,
            QSOFieldName::HAMLOGEU_QSO_UPLOAD_DATE => DataType::Date,
            QSOFieldName::HAMLOGEU_QSO_UPLOAD_STATUS => DataType::Enumeration(QsoUploadStatus),
            QSOFieldName::HAMQTH_QSO_UPLOAD_DATE => DataType::Date,
            QSOFieldName::HAMQTH_QSO_UPLOAD_STATUS => DataType::Enumeration(QsoUploadStatus),
            QSOFieldName::HRDLOG_QSO_UPLOAD_DATE => DataType::Date,
            QSOFieldName::HRDLOG_QSO_UPLOAD_STATUS => DataType::Enumeration(QsoUploadStatus),
            QSOFieldName::IOTA => DataType::IotaRefNo,
            QSOFieldName::IOTA_ISLAND_ID => DataType::PositiveInteger,
            QSOFieldName::ITUZ => DataType::PositiveInteger,
            QSOFieldName::K_INDEX => DataType::Integer,
            QSOFieldName::LAT => DataType::Location,
            QSOFieldName::LON => DataType::Location,
            QSOFieldName::LOTW_QSLRDATE => DataType::Date,
            QSOFieldName::LOTW_QSLSDATE => DataType::Date,
            QSOFieldName::LOTW_QSL_RCVD => DataType::Enumeration(QslRcvd),
            QSOFieldName::LOTW_QSL_SENT => DataType::Enumeration(QslSent),
            QSOFieldName::MAX_BURSTS => DataType::Number,
            QSOFieldName::MODE => DataType::Enumeration(Mode),
            QSOFieldName::MORSE_KEY_INFO => DataType::String,
            QSOFieldName::MORSE_KEY_TYPE => DataType::Enumeration(MorseKeyType),
            QSOFieldName::MS_SHOWER => DataType::String,
            QSOFieldName::MY_ALTITUDE => DataType::Number,
            QSOFieldName::MY_ANTENNA => DataType::String,
            QSOFieldName::MY_ANTENNA_INTL => DataType::IntlString,
            QSOFieldName::MY_ARRL_SECT => DataType::Enumeration(ArrlSection),
            QSOFieldName::MY_CITY => DataType::String,
            QSOFieldName::MY_CITY_INTL => DataType::IntlString,
            QSOFieldName::MY_CNTY => DataType::SecondarySubdivisionList,
            QSOFieldName::MY_CNTY_ALT => DataType::SecondaryAdministrativeSubdivisionListAlt,
            QSOFieldName::MY_COUNTRY => DataType::String,
            QSOFieldName::MY_COUNTRY_INTL => DataType::IntlString,
            QSOFieldName::MY_CQ_ZONE => DataType::PositiveInteger,
            QSOFieldName::MY_DARC_DOK => DataType::String,
            QSOFieldName::MY_DXCC => DataType::Enumeration(DxccEntityCode),
            QSOFieldName::MY_FISTS => DataType::PositiveInteger,
            QSOFieldName::MY_GRIDSQUARE => DataType::GridSquare,
            QSOFieldName::MY_GRIDSQUARE_EXT => DataType::GridSquareExt,
            QSOFieldName::MY_IOTA => DataType::IotaRefNo,
            QSOFieldName::MY_IOTA_ISLAND_ID => DataType::PositiveInteger,
            QSOFieldName::MY_ITU_ZONE => DataType::PositiveInteger,
            QSOFieldName::MY_LAT => DataType::Location,
            QSOFieldName::MY_LON => DataType::Location,
            QSOFieldName::MY_MORSE_KEY_INFO => DataType::String,
            QSOFieldName::MY_MORSE_KEY_TYPE => DataType::Enumeration(MorseKeyType),
            QSOFieldName::MY_NAME => DataType::String,
            QSOFieldName::MY_NAME_INTL => DataType::IntlString,
            QSOFieldName::MY_POSTAL_CODE => DataType::String,
            QSOFieldName::MY_POSTAL_CODE_INTL => DataType::IntlString,
            QSOFieldName::MY_POTA_REF => DataType::PotaRefList,
            QSOFieldName::MY_RIG => DataType::String,
            QSOFieldName::MY_RIG_INTL => DataType::IntlString,
            QSOFieldName::MY_SIG => DataType::String,
            QSOFieldName::MY_SIG_INTL => DataType::IntlString,
            QSOFieldName::MY_SIG_INFO => DataType::String,
            QSOFieldName::MY_SIG_INFO_INTL => DataType::IntlString,
            QSOFieldName::MY_SOTA_REF => DataType::SotaRef,
            QSOFieldName::MY_STATE => DataType::String,
            QSOFieldName::MY_STREET => DataType::String,
            QSOFieldName::MY_STREET_INTL => DataType::IntlString,
            QSOFieldName::MY_USACA_COUNTIES => DataType::SecondarySubdivisionList,
            QSOFieldName::MY_VUCC_GRIDS => DataType::GridSquareList,
            QSOFieldName::MY_WWFF_REF => DataType::WwffRef,
            QSOFieldName::NAME => DataType::String,
            QSOFieldName::NAME_INTL => DataType::IntlString,
            QSOFieldName::NOTES => DataType::MultilineString,
            QSOFieldName::NOTES_INTL => DataType::IntlMultilineString,
            QSOFieldName::NR_BURSTS => DataType::Integer,
            QSOFieldName::NR_PINGS => DataType::Integer,
            QSOFieldName::OPERATOR => DataType::String,
            QSOFieldName::OWNER_CALLSIGN => DataType::String,
            QSOFieldName::PFX => DataType::String,
            QSOFieldName::POTA_REF => DataType::PotaRef,
            QSOFieldName::PRECEDENCE => DataType::String,
            QSOFieldName::PROP_MODE => DataType::Enumeration(PropagationMode),
            QSOFieldName::PUBLIC_KEY => DataType::String,
            QSOFieldName::QRZCOM_QSO_DOWNLOAD_DATE => DataType::Date,
            QSOFieldName::QRZCOM_QSO_DOWNLOAD_STATUS => DataType::Enumeration(QslRcvd),
            QSOFieldName::QRZCOM_QSO_UPLOAD_DATE => DataType::Date,
            QSOFieldName::QRZCOM_QSO_UPLOAD_STATUS => DataType::Enumeration(QslRcvd),
            QSOFieldName::QSLMSG => DataType::MultilineString,
            QSOFieldName::QSLMSG_INTL => DataType::IntlMultilineString,
            QSOFieldName::QSLMSG_RCVD => DataType::MultilineString,
            QSOFieldName::QSLRDATE => DataType::Date,
            QSOFieldName::QSLSDATE => DataType::Date,
            QSOFieldName::QSL_RCVD => DataType::Enumeration(QslRcvd),
            QSOFieldName::QSL_RCVD_VIA => DataType::Enumeration(QslVia),
            QSOFieldName::QSL_SENT => DataType::Enumeration(QslSent),
            QSOFieldName::QSL_SENT_VIA => DataType::Enumeration(QslVia),
            QSOFieldName::QSL_VIA => DataType::String,
            QSOFieldName::QSO_COMPLETE => DataType::Enumeration(QsoComplete),
            QSOFieldName::QSO_DATE => DataType::Date,
            QSOFieldName::QSO_DATE_OFF => DataType::Date,
            QSOFieldName::QSO_RANDOM => DataType::Boolean,
            QSOFieldName::QTH => DataType::String,
            QSOFieldName::QTH_INTL => DataType::IntlString,
            QSOFieldName::REGION => DataType::Enumeration(Region),
            QSOFieldName::RIG => DataType::MultilineString,
            QSOFieldName::RIG_INTL => DataType::IntlMultilineString,
            QSOFieldName::RST_RCVD => DataType::String,
            QSOFieldName::RST_SENT => DataType::String,
            QSOFieldName::RX_PWR => DataType::Number,
            QSOFieldName::SAT_MODE => DataType::String,
            QSOFieldName::SAT_NAME => DataType::String,
            QSOFieldName::SFI => DataType::Integer,
            QSOFieldName::SIG => DataType::String,
            QSOFieldName::SIG_INTL => DataType::IntlString,
            QSOFieldName::SIG_INFO => DataType::String,
            QSOFieldName::SIG_INFO_INTL => DataType::IntlString,
            QSOFieldName::SILENT_KEY => DataType::Boolean,
            QSOFieldName::SKCC => DataType::String,
            QSOFieldName::SOTA_REF => DataType::SotaRef,
            QSOFieldName::SRX => DataType::Integer,
            QSOFieldName::SRX_STRING => DataType::String,
            QSOFieldName::STATE => DataType::String,
            QSOFieldName::STATION_CALLSIGN => DataType::String,
            QSOFieldName::STX => DataType::Integer,
            QSOFieldName::STX_STRING => DataType::String,
            QSOFieldName::SUBMODE => DataType::Enumeration(SubMode),
            QSOFieldName::SWL => DataType::Boolean,
            QSOFieldName::TEN_TEN => DataType::PositiveInteger,
            QSOFieldName::TIME_OFF => DataType::Time,
            QSOFieldName::TIME_ON => DataType::Time,
            QSOFieldName::TX_PWR => DataType::Number,
            QSOFieldName::UKSMG => DataType::PositiveInteger,
            QSOFieldName::USACA_COUNTIES => DataType::SecondarySubdivisionList,
            QSOFieldName::VE_PROV => DataType::String,
            QSOFieldName::VUCC_GRIDS => DataType::GridSquareList,
            QSOFieldName::WEB => DataType::String,
            QSOFieldName::WWFF_REF => DataType::WwffRef,
        }
    }
}
