use crate::data::AdifData;
use crate::error::AdifError;
use adif_macros::{AdifData, AutoDisplay, AutoTestEnum};

#[derive(Debug, Clone, PartialEq, Eq, AutoDisplay, AdifData, AutoTestEnum)]
pub enum ArrlSection {
    #[adif("AL")]
    Alabama,
    #[adif("AK")]
    Alaska,
    #[adif("AB")]
    Alberta,
    #[adif("AR")]
    Arkansas,
    #[adif("AZ")]
    Arizona,
    #[adif("BC")]
    BritishColumbia,
    #[adif("CO")]
    Colorado,
    #[adif("CT")]
    Connecticut,
    #[adif("DE")]
    Delaware,
    #[adif("EB")]
    EastBay,
    #[adif("EMA")]
    EasternMassachusetts,
    #[adif("ENY")]
    EasternNewYork,
    #[adif("EPA")]
    EasternPennsylvania,
    #[adif("EWA")]
    EasternWashington,
    #[adif("GA")]
    Georgia,
    #[adif("GTA")]
    GreaterToronto,
    #[adif("ID")]
    Idaho,
    #[adif("IL")]
    Illinois,
    #[adif("IN")]
    Indiana,
    #[adif("IA")]
    Iowa,
    #[adif("KS")]
    Kansas,
    #[adif("KY")]
    Kentucky,
    #[adif("LAX")]
    LosAngeles,
    #[adif("LA")]
    Louisiana,
    #[adif("ME")]
    Maine,
    #[adif("MB")]
    Manitoba,
    #[adif("MAR")]
    Maritime,
    #[adif("MDC")]
    MarylandDC,
    #[adif("MI")]
    Michigan,
    #[adif("MN")]
    Minnesota,
    #[adif("MS")]
    Mississippi,
    #[adif("MO")]
    Missouri,
    #[adif("MT")]
    Montana,
    #[adif("NE")]
    Nebraska,
    #[adif("NV")]
    Nevada,
    #[adif("NH")]
    NewHampshire,
    #[adif("NM")]
    NewMexico,
    #[adif("NLI")]
    NewYorkCityLongIsland,
    #[adif("NL")]
    NewfoundlandLabrador,
    #[adif("NC")]
    NorthCarolina,
    #[adif("ND")]
    NorthDakota,
    #[adif("NTX")]
    NorthTexas,
    #[adif("NFL")]
    NorthernFlorida,
    #[adif("NNJ")]
    NorthernNewJersey,
    #[adif("NNY")]
    NorthernNewYork,
    #[adif("NT")]
    NorthwestTerritoriesYukonNunavut,
    #[adif("NWT")]
    Northwest,
    #[adif("OH")]
    Ohio,
    #[adif("OK")]
    Oklahoma,
    #[adif("ON")]
    Ontario,
    #[adif("ONE")]
    OntarioEast,
    #[adif("ONN")]
    OntarioNorth,
    #[adif("ONS")]
    OntarioSouth,
    #[adif("ORG")]
    Orange,
    #[adif("OR")]
    Oregon,
    #[adif("PAC")]
    Pacific,
    #[adif("PE")]
    PrinceEdwardIsland,
    #[adif("PR")]
    PuertoRico,
    #[adif("QC")]
    Quebec,
    #[adif("RI")]
    RhodeIsland,
    #[adif("SV")]
    SacramentoValley,
    #[adif("SDG")]
    SanDiego,
    #[adif("SF")]
    SanFrancisco,
    #[adif("SJV")]
    SanJoaquinValley,
    #[adif("SB")]
    SantaBarbara,
    #[adif("SCV")]
    SantaClaraValley,
    #[adif("SK")]
    Saskatchewan,
    #[adif("SC")]
    SouthCarolina,
    #[adif("SD")]
    SouthDakota,
    #[adif("STX")]
    SouthTexas,
    #[adif("SFL")]
    SouthernFlorida,
    #[adif("SNJ")]
    SouthernNewJersey,
    #[adif("TN")]
    Tennessee,
    #[adif("VI")]
    USVirginIslands,
    #[adif("UT")]
    Utah,
    #[adif("VT")]
    Vermont,
    #[adif("VA")]
    Virginia,
    #[adif("WCF")]
    WestCentralFlorida,
    #[adif("WTX")]
    WestTexas,
    #[adif("WV")]
    WestVirginia,
    #[adif("WMA")]
    WesternMassachusetts,
    #[adif("WNY")]
    WesternNewYork,
    #[adif("WPA")]
    WesternPennsylvania,
    #[adif("WWA")]
    WesternWashington,
    #[adif("WI")]
    Wisconsin,
    #[adif("WY")]
    Wyoming,
}
