use crate::data::AdifData;
use crate::error::AdifError;
use radif_macros::{AdifData, AutoDisplay, AutoTestEnum};

#[derive(Debug, Clone, PartialEq, Eq, AutoDisplay, AdifData, AutoTestEnum)]
pub enum Band {
    #[adif("2190m")]
    Band2190m,
    #[adif("630m")]
    Band630m,
    #[adif("560m")]
    Band560m,
    #[adif("160m")]
    Band160m,
    #[adif("80m")]
    Band80m,
    #[adif("60m")]
    Band60m,
    #[adif("40m")]
    Band40m,
    #[adif("30m")]
    Band30m,
    #[adif("20m")]
    Band20m,
    #[adif("17m")]
    Band17m,
    #[adif("15m")]
    Band15m,
    #[adif("12m")]
    Band12m,
    #[adif("10m")]
    Band10m,
    #[adif("8m")]
    Band8m,
    #[adif("6m")]
    Band6m,
    #[adif("5m")]
    Band5m,
    #[adif("4m")]
    Band4m,
    #[adif("2m")]
    Band2m,
    #[adif("1.25m")]
    Band1_25m,
    #[adif("70cm")]
    Band70cm,
    #[adif("33cm")]
    Band33cm,
    #[adif("23cm")]
    Band23cm,
    #[adif("13cm")]
    Band13cm,
    #[adif("9cm")]
    Band9cm,
    #[adif("6cm")]
    Band6cm,
    #[adif("3cm")]
    Band3cm,
    #[adif("1.25cm")]
    Band1_25cm,
    #[adif("6mm")]
    Band6mm,
    #[adif("4mm")]
    Band4mm,
    #[adif("2.5mm")]
    Band2_5mm,
    #[adif("2mm")]
    Band2mm,
    #[adif("1mm")]
    Band1mm,
    #[adif("submm")]
    Bandsubmm,
}
