use crate::data::AdifData;
use crate::error::AdifError;
use adif_macros::{AdifData, AutoDisplay, AutoTestEnum};

#[derive(Debug, Clone, PartialEq, Eq, AutoDisplay, AdifData, AutoTestEnum)]
pub enum ContestId {
    #[adif("070-160M-SPRINT")]
    PODXSGreatPumpkinSprint,
    #[adif("070-3-DAY")]
    PODXSThreeDayWeekend,
    #[adif("070-31-FLAVORS")]
    PODXS31Flavors,
    #[adif("070-40M-SPRINT")]
    PODXS40mFirecrackerSprint,
    #[adif("070-80M-SPRINT")]
    PODXS80mJayHudakMemorialSprint,
    #[adif("070-PSKFEST")]
    PODXSPSKFest,
    #[adif("070-ST-PATS-DAY")]
    PODXSStPatricksDay,
    #[adif("070-VALENTINE-SPRINT")]
    PODXSValentineSprint,
    #[adif("10-RTTY")]
    TenMeterRTTYContest,
    #[adif("1010-OPEN-SEASON")]
    OpenSeasonTenMeterQSOParty,
    #[adif("7QP")]
    Area7thQSOParty,
    #[adif("AL-QSO-PARTY")]
    AlabamaQSOParty,
    #[adif("ALL-ASIAN-DX-CW")]
    JARLAllAsianDXContestCW,
    #[adif("ALL-ASIAN-DX-PHONE")]
    JARLAllAsianDXContestPHONE,
    #[adif("ANARTS-RTTY")]
    ANARTSWWRTTY,
    #[adif("ANATOLIAN-RTTY")]
    AnatolianWWRTTY,
    #[adif("AP-SPRINT")]
    AsiaPacificSprint,
    #[adif("AR-QSO-PARTY")]
    ArkansasQSOParty,
    #[adif("ARI-DX")]
    ARIDXContest,
    #[adif("ARRL-10")]
    ARRL10MeterContest,
    #[adif("ARRL-10-GHZ")]
    ARRL10GHzandUpContest,
    #[adif("ARRL-160")]
    ARRL160MeterContest,
    #[adif("ARRL-222")]
    ARRL222MHzandUpDistanceContest,
    #[adif("ARRL-DIGI")]
    ARRLInternationalDigitalContest,
    #[adif("ARRL-DX-CW")]
    ARRLInternationalDXContestCW,
    #[adif("ARRL-DX-SSB")]
    ARRLInternationalDXContestPhone,
    #[adif("ARRL-EME")]
    ARRLEMEcontest,
    #[adif("ARRL-FIELD-DAY")]
    ARRLFieldDay,
    #[adif("ARRL-RR-CW")]
    ARRLRookieRoundupCW,
    #[adif("ARRL-RR-RTTY")]
    ARRLRookieRoundupRTTY,
    #[adif("ARRL-RR-SSB")]
    ARRLRookieRoundupPhone,
    #[adif("ARRL-RTTY")]
    ARRLRTTYRoundUp,
    #[adif("ARRL-SCR")]
    ARRLSchoolClubRoundup,
    #[adif("ARRL-SS-CW")]
    ARRLNovemberSweepstakesCW,
    #[adif("ARRL-SS-SSB")]
    ARRLNovemberSweepstakesPhone,
    #[adif("ARRL-UHF-AUG")]
    ARRLAugustUHFContest,
    #[adif("ARRL-VHF-JAN")]
    ARRLJanuaryVHFSweepstakes,
    #[adif("ARRL-VHF-JUN")]
    ARRLJuneVHFQSOParty,
    #[adif("ARRL-VHF-SEP")]
    ARRLSeptemberVHFQSOParty,
    #[adif("AZ-QSO-PARTY")]
    ArizonaQSOParty,
    #[adif("BARTG-RTTY")]
    BARTGSpringRTTYContest,
    #[adif("BARTG-SPRINT")]
    BARTGSprintContest,
    #[adif("BC-QSO-PARTY")]
    BritishColumbiaQSOParty,
    #[adif("CA-QSO-PARTY")]
    CaliforniaQSOParty,
    #[adif("CIS-DX")]
    CISDXContest,
    #[adif("CO-QSO-PARTY")]
    ColoradoQSOParty,
    #[adif("CQ-160-CW")]
    CQWW160MeterDXContestCW,
    #[adif("CQ-160-SSB")]
    CQWW160MeterDXContestSSB,
    #[adif("CQ-M")]
    CQMInternationalDXContest,
    #[adif("CQ-VHF")]
    CQWorldWideVHFContest,
    #[adif("CQ-WPX-CW")]
    CQWWWPXContestCW,
    #[adif("CQ-WPX-RTTY")]
    CQRJWWRTTYWPXContest,
    #[adif("CQ-WPX-SSB")]
    CQWWWPXContestSSB,
    #[adif("CQ-WW-CW")]
    CQWWDXContestCW,
    #[adif("CQ-WW-RTTY")]
    CQRJWWRTTYDXContest,
    #[adif("CQ-WW-SSB")]
    CQWWDXContestSSB,
    #[adif("CT-QSO-PARTY")]
    ConnecticutQSOParty,
    #[adif("CVA-DX-CW")]
    ConcursoVerdeeAmareloDXCWContest,
    #[adif("CVA-DX-SSB")]
    ConcursoVerdeeAmareloDXSSBContest,
    #[adif("CWOPS-CW-OPEN")]
    CWopsCWOpenCompetition,
    #[adif("CWOPS-CWT")]
    CWopsMiniCWTTest,
    #[adif("DARC-WAEDC-CW")]
    WAEDXContestCW,
    #[adif("DARC-WAEDC-RTTY")]
    WAEDXContestRTTY,
    #[adif("DARC-WAEDC-SSB")]
    WAEDXContestSSB,
    #[adif("DARC-WAG")]
    DARCWorkedAllGermany,
    #[adif("DE-QSO-PARTY")]
    DelawareQSOParty,
    #[adif("DL-DX-RTTY")]
    DLDXRTTYContest,
    #[adif("DMC-RTTY")]
    DMCRTTYContest,
    #[adif("EA-CNCW")]
    ConcursoNacionaldeTelegrafia,
    #[adif("EA-DME")]
    MunicipiosEspanoles,
    #[adif("EA-MAJESTAD-CW")]
    HisMajestyTheKingofSpainCWContest,
    #[adif("EA-MAJESTAD-SSB")]
    HisMajestyTheKingofSpainSSBContest,
    #[adif("EA-PSK63")]
    EAPSK63,
    #[adif("EA-RTTY(import-only)")]
    UniondeRadioaficionadosEspanolesRTTYContestImport,
    #[adif("EA-SMRE-CW")]
    SuMajestadElReydeEspanaCW,
    #[adif("EA-SMRE-SSB")]
    SuMajestadElReydeEspanaSSB,
    #[adif("EA-VHF-ATLANTIC")]
    AtlanticoVUHF,
    #[adif("EA-VHF-COM")]
    CombinadodeVUHF,
    #[adif("EA-VHF-COSTA-SOL")]
    CostadelSolVUHF,
    #[adif("EA-VHF-EA")]
    NacionalVHF,
    #[adif("EA-VHF-EA1RCS")]
    SegoviaEA1RCSVUHF,
    #[adif("EA-VHF-QSL")]
    QSLVUHF50MHz,
    #[adif("EA-VHF-SADURNI")]
    SantSadurniVUHF,
    #[adif("EA-WW-RTTY")]
    UniondeRadioaficionadosEspanolesRTTYContest,
    #[adif("EPC-PSK63")]
    PSK63QSOParty,
    #[adif("EUSprint")]
    EUSprint,
    #[adif("EU-HF")]
    EUHFChampionship,
    #[adif("EU-PSK-DX")]
    EUPSKDXContest,
    #[adif("EUCW160M")]
    EuropeanCWAssociation160mCWParty,
    #[adif("FALLSPRINT")]
    FISTSFallSprint,
    #[adif("FL-QSO-PARTY")]
    FloridaQSOParty,
    #[adif("GA-QSO-PARTY")]
    GeorgiaQSOParty,
    #[adif("HA-DX")]
    HungarianDXContest,
    #[adif("HELVETIA")]
    HelvetiaContest,
    #[adif("HI-QSO-PARTY")]
    HawaiianQSOParty,
    #[adif("HOLYLAND")]
    IARCHolylandContest,
    #[adif("IA-QSO-PARTY")]
    IowaQSOParty,
    #[adif("IARU-FIELD-DAY")]
    DARCIARURegion1FieldDay,
    #[adif("IARU-HF")]
    IARUHFWorldChampionship,
    #[adif("ICWC-MST")]
    ICWCMediumSpeedTest,
    #[adif("ID-QSO-PARTY")]
    IdahoQSOParty,
    #[adif("ILQSOParty")]
    IllinoisQSOParty,
    #[adif("IN-QSO-PARTY")]
    IndianaQSOParty,
    #[adif("JARTS-WW-RTTY")]
    JARTSWWRTTY,
    #[adif("JIDX-CW")]
    JapanInternationalDXContestCW,
    #[adif("JIDX-SSB")]
    JapanInternationalDXContestSSB,
    #[adif("JT-DX-RTTY")]
    MongolianRTTYDXContest,
    #[adif("K1USN-SST")]
    K1USNSlowSpeedTest,
    #[adif("KS-QSO-PARTY")]
    KansasQSOParty,
    #[adif("KY-QSO-PARTY")]
    KentuckyQSOParty,
    #[adif("LA-QSO-PARTY")]
    LouisianaQSOParty,
    #[adif("LDC-RTTY")]
    DRCGLongDistanceContestRTTY,
    #[adif("LZDX")]
    LZDXContest,
    #[adif("MAR-QSO-PARTY")]
    MaritimesQSOParty,
    #[adif("MD-QSO-PARTY")]
    MarylandQSOParty,
    #[adif("ME-QSO-PARTY")]
    MaineQSOParty,
    #[adif("MI-QSO-PARTY")]
    MichiganQSOParty,
    #[adif("MIDATLANTIC-QSO-PARTY")]
    MidAtlanticQSOParty,
    #[adif("MN-QSO-PARTY")]
    MinnesotaQSOParty,
    #[adif("MO-QSO-PARTY")]
    MissouriQSOParty,
    #[adif("MS-QSO-PARTY")]
    MississippiQSOParty,
    #[adif("MT-QSO-PARTY")]
    MontanaQSOParty,
    #[adif("NA-SPRINT-CW")]
    NorthAmericaSprintCW,
    #[adif("NA-SPRINT-RTTY")]
    NorthAmericaSprintRTTY,
    #[adif("NA-SPRINT-SSB")]
    NorthAmericaSprintPhone,
    #[adif("NAQP-CW")]
    NorthAmericaQSOPartyCW,
    #[adif("NAQP-RTTY")]
    NorthAmericaQSOPartyRTTY,
    #[adif("NAQP-SSB")]
    NorthAmericaQSOPartyPhone,
    #[adif("NC-QSO-PARTY")]
    NorthCarolinaQSOParty,
    #[adif("ND-QSO-PARTY")]
    NorthDakotaQSOParty,
    #[adif("NE-QSO-PARTY")]
    NebraskaQSOParty,
    #[adif("NEQP")]
    NewEnglandQSOParty,
    #[adif("NH-QSO-PARTY")]
    NewHampshireQSOParty,
    #[adif("NJ-QSO-PARTY")]
    NewJerseyQSOParty,
    #[adif("NM-QSO-PARTY")]
    NewMexicoQSOParty,
    #[adif("NRAU-BALTIC-CW")]
    NRAUBalticContestCW,
    #[adif("NRAU-BALTIC-SSB")]
    NRAUBalticContestSSB,
    #[adif("NV-QSO-PARTY")]
    NevadaQSOParty,
    #[adif("NY-QSO-PARTY")]
    NewYorkQSOParty,
    #[adif("OCEANIA-DX-CW")]
    OceaniaDXContestCW,
    #[adif("OCEANIA-DX-SSB")]
    OceaniaDXContestSSB,
    #[adif("OH-QSO-PARTY")]
    OhioQSOParty,
    #[adif("OK-DX-RTTY")]
    CzechRadioClubOKDXContest,
    #[adif("OK-OM-DX")]
    CzechRadioClubOKOMDXContest,
    #[adif("OK-QSO-PARTY")]
    OklahomaQSOParty,
    #[adif("OMISS-QSO-PARTY")]
    OldManInternationalSidebandSocietyQSOParty,
    #[adif("ON-QSO-PARTY")]
    OntarioQSOParty,
    #[adif("OR-QSO-PARTY")]
    OregonQSOParty,
    #[adif("PA-QSO-PARTY")]
    PennsylvaniaQSOParty,
    #[adif("PACC")]
    DutchPACCContest,
    #[adif("PSK-DEATHMATCH")]
    MDXAPSKDeathMatch,
    #[adif("QC-QSO-PARTY")]
    QuebecQSOParty,
    #[adif("RAC(import-only)")]
    CanadianAmateurRadioSocietyContest,
    #[adif("RAC-CANADA-DAY")]
    RACCanadaDayContest,
    #[adif("RAC-CANADA-WINTER")]
    RACCanadaWinterContest,
    #[adif("RDAC")]
    RussianDistrictAwardContest,
    #[adif("RDXC")]
    RussianDXContest,
    #[adif("REF-160M")]
    ReseaudesEmetteursFrancais160mContest,
    #[adif("REF-CW")]
    ReseaudesEmetteursFrancaisContestCW,
    #[adif("REF-SSB")]
    ReseaudesEmetteursFrancaisContestSSB,
    #[adif("REP-PORTUGAL-DAY-HF")]
    RededosEmissoresPortuguesesPortugalDayHFContest,
    #[adif("RI-QSO-PARTY")]
    RhodeIslandQSOParty,
    #[adif("RSGB-160")]
    RSGB1_8MHzContest,
    #[adif("RSGB-21/28-CW")]
    RSGB2128MHzContestCW,
    #[adif("RSGB-21/28-SSB")]
    RSGB2128MHzContestSSB,
    #[adif("RSGB-80M-CC")]
    RSGB80mClubChampionships,
    #[adif("RSGB-AFS-CW")]
    AffiliatedSocietiesTeamContestCW,
    #[adif("RSGB-AFS-SSB")]
    AffiliatedSocietiesTeamContestSSB,
    #[adif("RSGB-CLUB-CALLS")]
    ClubCalls,
    #[adif("RSGB-COMMONWEALTH")]
    CommonwealthContest,
    #[adif("RSGB-IOTA")]
    IOTAContest,
    #[adif("RSGB-LOW-POWER")]
    LowPowerFieldDay,
    #[adif("RSGB-NFD")]
    NationalFieldDay,
    #[adif("RSGB-ROPOCO")]
    RoPoCo,
    #[adif("RSGB-SSB-FD")]
    SSBFieldDay,
    #[adif("RUSSIAN-RTTY")]
    RussianRadioRTTYWorldwideContest,
    #[adif("SAC-CW")]
    ScandinavianActivityContestCW,
    #[adif("SAC-SSB")]
    ScandinavianActivityContestSSB,
    #[adif("SARTG-RTTY")]
    SARTGWWRTTY,
    #[adif("SC-QSO-PARTY")]
    SouthCarolinaQSOParty,
    #[adif("SCC-RTTY")]
    SCCRTTYChampionship,
    #[adif("SD-QSO-PARTY")]
    SouthDakotaQSOParty,
    #[adif("SMP-AUG")]
    SSAPortabeltestAugust,
    #[adif("SMP-MAY")]
    SSAPortabeltestMay,
    #[adif("SP-DX-RTTY")]
    PRCSPDXContestRTTY,
    #[adif("SPAR-WINTER-FD")]
    SPARWinterFieldDay,
    #[adif("SPDXContest")]
    SPDXContest,
    #[adif("SPRINGSPRINT")]
    FISTSSpringSprint,
    #[adif("SR-MARATHON")]
    ScottishRussianMarathon,
    #[adif("STEW-PERRY")]
    StewPerryTopbandDistanceChallenge,
    #[adif("SUMMERSPRINT")]
    FISTSSummerSprint,
    #[adif("TARA-GRID-DIP")]
    TARAGridDipPSKRTTYShindig,
    #[adif("TARA-RTTY")]
    TARARTTYMelee,
    #[adif("TARA-RUMBLE")]
    TARARumblePSKContest,
    #[adif("TARA-SKIRMISH")]
    TARASkirmishDigitalPrefixContest,
    #[adif("TEN-RTTY")]
    TenMeterRTTYContestOld,
    #[adif("TMC-RTTY")]
    TheMakrothenContest,
    #[adif("TN-QSO-PARTY")]
    TennesseeQSOParty,
    #[adif("TX-QSO-PARTY")]
    TexasQSOParty,
    #[adif("UBA-DX-CW")]
    UBAContestCW,
    #[adif("UBA-DX-SSB")]
    UBAContestSSB,
    #[adif("UK-DX-BPSK63")]
    EuropeanPSKClubBPSK63Contest,
    #[adif("UK-DX-RTTY")]
    UKDXRTTYContest,
    #[adif("UKR-CHAMP-RTTY")]
    OpenUkraineRTTYChampionship,
    #[adif("UKRAINIANDX")]
    UkrainianDX,
    #[adif("UKSMG-6M-MARATHON")]
    UKSMG6mMarathon,
    #[adif("UKSMG-SUMMER-ES")]
    UKSMGSummerEsContest,
    #[adif("URE-DX(import-only)")]
    UkrainianDXContest,
    #[adif("US-COUNTIES-QSO")]
    MobileAmateurAwardsClub,
    #[adif("UT-QSO-PARTY")]
    UtahQSOParty,
    #[adif("VA-QSO-PARTY")]
    VirginiaQSOParty,
    #[adif("VENEZ-IND-DAY")]
    RCVVenezuelanIndependenceDayContest,
    #[adif("VIRGINIAQSOPARTY")]
    VirginiaQSOPartyImport,
    #[adif("VOLTA-RTTY")]
    AlessandroVoltaRTTYDXContest,
    #[adif("VT-QSO-PARTY")]
    VermontQSOParty,
    #[adif("WA-QSO-PARTY")]
    WashingtonQSOParty,
    #[adif("WFD")]
    WinterFieldDay,
    #[adif("WI-QSO-PARTY")]
    WisconsinQSOParty,
    #[adif("WIA-HARRYANGEL")]
    WIAHarryAngelMemorial80mSprint,
    #[adif("WIA-JMMFD")]
    WIAJohnMoyleMemorialFieldDay,
    #[adif("WIA-OCDX")]
    WIAOceaniaDXContest,
    #[adif("WIA-REMEMBRANCE")]
    WIARemembranceDay,
    #[adif("WIA-ROSSHULL")]
    WIARossHullMemorialVHFUHFContest,
    #[adif("WIA-TRANSTASMAN")]
    WIATransTasmanLowBandsChallenge,
    #[adif("WIA-VHF/UHFFD")]
    WIAVHFUHFFieldDays,
    #[adif("WIA-VKSHIRES")]
    WIAVKShires,
    #[adif("WINTERSPRINT")]
    FISTSWinterSprint,
    #[adif("WV-QSO-PARTY")]
    WestVirginiaQSOParty,
    #[adif("WW-DIGI")]
    WorldWideDigiDXContest,
    #[adif("WY-QSO-PARTY")]
    WyomingQSOParty,
    #[adif("XE-INTL-RTTY")]
    MexicoInternationalContestRTTY,
    #[adif("YOHFDX")]
    YODXHFcontest,
    #[adif("YUDXC")]
    YUDXContest,
}
