use crate::data::AdifData;
use crate::error::AdifError;
use adif_macros::{AdifData, AutoDisplay, AutoTestEnum};

#[derive(Debug, Clone, PartialEq, Eq, AutoDisplay, AdifData, AutoTestEnum)]
#[allow(non_camel_case_types)]
pub enum Credit {
    #[adif("CQDX")]
    CQMagazineDXMixed,
    #[adif("CQDX_BAND")]
    CQMagazineDXBand,
    #[adif("CQDX_MODE")]
    CQMagazineDXMode,
    #[adif("CQDX_MOBILE")]
    CQMagazineDXMobile,
    #[adif("CQDX_QRP")]
    CQMagazineDXQRP,
    #[adif("CQDX_SATELLITE")]
    CQMagazineDXSatellite,
    #[adif("CQDXFIELD")]
    CQMagazineDXFieldMixed,
    #[adif("CQDXFIELD_BAND")]
    CQMagazineDXFieldBand,
    #[adif("CQDXFIELD_MODE")]
    CQMagazineDXFieldMode,
    #[adif("CQDXFIELD_MOBILE")]
    CQMagazineDXFieldMobile,
    #[adif("CQDXFIELD_QRP")]
    CQMagazineDXFieldQRP,
    #[adif("CQDXFIELD_SATELLITE")]
    CQMagazineDXFieldSatellite,
    #[adif("CQWAZ_MIXED")]
    CQMagazineWorkedAllZonesWAZMixed,
    #[adif("CQWAZ_BAND")]
    CQMagazineWorkedAllZonesWAZBand,
    #[adif("CQWAZ_MODE")]
    CQMagazineWorkedAllZonesWAZMode,
    #[adif("CQWAZ_SATELLITE")]
    CQMagazineWorkedAllZonesWAZSatellite,
    #[adif("CQWAZ_EME")]
    CQMagazineWorkedAllZonesWAZEME,
    #[adif("CQWAZ_MOBILE")]
    CQMagazineWorkedAllZonesWAZMobile,
    #[adif("CQWAZ_QRP")]
    CQMagazineWorkedAllZonesWAZQRP,
    #[adif("CQWPX")]
    CQMagazineWPXMixed,
    #[adif("CQWPX_BAND")]
    CQMagazineWPXBand,
    #[adif("CQWPX_MODE")]
    CQMagazineWPXMode,
    #[adif("DXCC")]
    ARRLDXCenturyClubDXCCMixed,
    #[adif("DXCC_BAND")]
    ARRLDXCenturyClubDXCCBand,
    #[adif("DXCC_MODE")]
    ARRLDXCenturyClubDXCCMode,
    #[adif("DXCC_SATELLITE")]
    ARRLDXCenturyClubDXCCSatellite,
    #[adif("EAUSTRALIA")]
    eQSLeAustraliaMixed,
    #[adif("ECANADA")]
    eQSLeCanadaMixed,
    #[adif("ECOUNTY_STATE")]
    eQSLeCountyState,
    #[adif("EDX")]
    eQSLeDXMixed,
    #[adif("EDX100")]
    eQSLeDX100Mixed,
    #[adif("EDX100_BAND")]
    eQSLeDX100Band,
    #[adif("EDX100_MODE")]
    eQSLeDX100Mode,
    #[adif("EECHOLINK50")]
    eQSLeEcholink50Echolink,
    #[adif("EGRID_BAND")]
    eQSLeGridBand,
    #[adif("EGRID_SATELLITE")]
    eQSLeGridSatellite,
    #[adif("EPFX300")]
    eQSLePfx300Mixed,
    #[adif("EPFX300_MODE")]
    eQSLePfx300Mode,
    #[adif("EWAS")]
    eQSLeWASMixed,
    #[adif("EWAS_BAND")]
    eQSLeWASBand,
    #[adif("EWAS_MODE")]
    eQSLeWASMode,
    #[adif("EWAS_SATELLITE")]
    eQSLeWASSatellite,
    #[adif("EZ40")]
    eQSLeZ40Mixed,
    #[adif("EZ40_MODE")]
    eQSLeZ40Mode,
    #[adif("FFMA")]
    ARRLFredFishMemorialAwardFFMAMixed,
    #[adif("IOTA")]
    RSGBIslandsontheAirIOTAMixed,
    #[adif("IOTA_BASIC")]
    RSGBIslandsontheAirIOTABasicMixed,
    #[adif("IOTA_CONT")]
    RSGBIslandsontheAirIOTAContinent,
    #[adif("IOTA_GROUP")]
    RSGBIslandsontheAirIOTAGroup,
    #[adif("RDA")]
    TAGRussianDistrictsAwardRDAMixed,
    #[adif("USACA")]
    CQMagazineUnitedStatesofAmericaCountiesUSACAMixed,
    #[adif("VUCC_BAND")]
    ARRLVHFUHFCenturyClubProgramVUCCBand,
    #[adif("VUCC_SATELLITE")]
    ARRLVHFUHFCenturyClubProgramVUCCSatellite,
    #[adif("WAB")]
    WABAGWorkedAllBritainWABMixed,
    #[adif("WAC")]
    IARUWorkedAllContinentsWACMixed,
    #[adif("WAC_BAND")]
    IARUWorkedAllContinentsWACBand,
    #[adif("WAE")]
    DARCWorkedAllEuropeWAEMixed,
    #[adif("WAE_BAND")]
    DARCWorkedAllEuropeWAEBand,
    #[adif("WAE_MODE")]
    DARCWorkedAllEuropeWAEMode,
    #[adif("WAIP")]
    ARIWorkedAllItalianProvincesWAIPMixed,
    #[adif("WAIP_BAND")]
    ARIWorkedAllItalianProvincesWAIPBand,
    #[adif("WAIP_MODE")]
    ARIWorkedAllItalianProvincesWAIPMode,
    #[adif("WAS")]
    ARRLWorkedAllStatesWASMixed,
    #[adif("WAS_BAND")]
    ARRLWorkedAllStatesWASBand,
    #[adif("WAS_EME")]
    ARRLWorkedAllStatesWASEME,
    #[adif("WAS_MODE")]
    ARRLWorkedAllStatesWASMode,
    #[adif("WAS_NOVICE")]
    ARRLWorkedAllStatesWASNovice,
    #[adif("WAS_QRP")]
    ARRLWorkedAllStatesWASQRP,
    #[adif("WAS_SATELLITE")]
    ARRLWorkedAllStatesWASSatellite,
    #[adif("WITUZ")]
    RSGBWorkedITUZonesWITUZMixed,
    #[adif("WITUZ_BAND")]
    RSGBWorkedITUZonesWITUZBand,
}
