/*
 * radif
 * Copyright (C) 2025 - Luca Cireddu (IS0GVH) <sardylan@gmail.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

use crate::data::AdifData;
use crate::error::AdifError;
use radif_macros::{AdifData, AutoDisplay, AutoTestEnum};

#[derive(Debug, Clone, PartialEq, Eq, AutoDisplay, AdifData, AutoTestEnum)]
pub enum Mode {
    #[adif("AM")]
    AM,
    #[adif("ARDOP")]
    ARDOP,
    #[adif("ATV")]
    ATV,
    #[adif("CHIP")]
    CHIP,
    #[adif("CLO")]
    CLO,
    #[adif("CONTESTI")]
    CONTESTI,
    #[adif("CW")]
    CW,
    #[adif("DIGITALVOICE")]
    DIGITALVOICE,
    #[adif("DOMINO")]
    DOMINO,
    #[adif("DYNAMIC")]
    DYNAMIC,
    #[adif("FAX")]
    FAX,
    #[adif("FM")]
    FM,
    #[adif("FSK441")]
    FSK441,
    #[adif("FT8")]
    FT8,
    #[adif("HELL")]
    HELL,
    #[adif("ISCAT")]
    ISCAT,
    #[adif("JT4")]
    JT4,
    #[adif("JT6M")]
    JT6M,
    #[adif("JT9")]
    JT9,
    #[adif("JT44")]
    JT44,
    #[adif("JT65")]
    JT65,
    #[adif("MFSK")]
    MFSK,
    #[adif("MSK144")]
    MSK144,
    #[adif("MT63")]
    MT63,
    #[adif("OLIVIA")]
    OLIVIA,
    #[adif("OPERA")]
    OPERA,
    #[adif("PAC")]
    PAC,
    #[adif("PAX")]
    PAX,
    #[adif("PKT")]
    PKT,
    #[adif("PSK")]
    PSK,
    #[adif("PSK2K")]
    PSK2K,
    #[adif("Q15")]
    Q15,
    #[adif("QRA64")]
    QRA64,
    #[adif("ROS")]
    ROS,
    #[adif("RTTY")]
    RTTY,
    #[adif("RTTYM")]
    RTTYM,
    #[adif("SSB")]
    SSB,
    #[adif("SSTV")]
    SSTV,
    #[adif("T10")]
    T10,
    #[adif("THOR")]
    THOR,
    #[adif("THRB")]
    THRB,
    #[adif("TOR")]
    TOR,
    #[adif("V4")]
    V4,
    #[adif("VOI")]
    VOI,
    #[adif("WINMOR")]
    WINMOR,
    #[adif("WSPR")]
    WSPR,
    #[adif("AMTORFEC")]
    AMTORFEC,
    #[adif("ASCI")]
    ASCI,
    #[adif("C4FM")]
    C4FM,
    #[adif("CHIP64")]
    CHIP64,
    #[adif("CHIP128")]
    CHIP128,
    #[adif("DOMINOF")]
    DOMINOF,
    #[adif("DSTAR")]
    DSTAR,
    #[adif("FMHELL")]
    FMHELL,
    #[adif("FSK31")]
    FSK31,
    #[adif("GTOR")]
    GTOR,
    #[adif("HELL80")]
    HELL80,
    #[adif("HFSK")]
    HFSK,
    #[adif("JT4A")]
    JT4A,
    #[adif("JT4B")]
    JT4B,
    #[adif("JT4C")]
    JT4C,
    #[adif("JT4D")]
    JT4D,
    #[adif("JT4E")]
    JT4E,
    #[adif("JT4F")]
    JT4F,
    #[adif("JT4G")]
    JT4G,
    #[adif("JT65A")]
    JT65A,
    #[adif("JT65B")]
    JT65B,
    #[adif("JT65C")]
    JT65C,
    #[adif("MFSK8")]
    MFSK8,
    #[adif("MFSK16")]
    MFSK16,
    #[adif("PAC2")]
    PAC2,
    #[adif("PAC3")]
    PAC3,
    #[adif("PAX2")]
    PAX2,
    #[adif("PCW")]
    PCW,
    #[adif("PSK10")]
    PSK10,
    #[adif("PSK31")]
    PSK31,
    #[adif("PSK63")]
    PSK63,
    #[adif("PSK63F")]
    PSK63F,
    #[adif("PSK125")]
    PSK125,
    #[adif("PSKAM10")]
    PSKAM10,
    #[adif("PSKAM31")]
    PSKAM31,
    #[adif("PSKAM50")]
    PSKAM50,
    #[adif("PSKFEC31")]
    PSKFEC31,
    #[adif("PSKHELL")]
    PSKHELL,
    #[adif("QPSK31")]
    QPSK31,
    #[adif("QPSK63")]
    QPSK63,
    #[adif("QPSK125")]
    QPSK125,
    #[adif("THRBX")]
    THRBX,
}
